import type { Metadata } from "next";
import { Recursive } from "next/font/google";
import "../globals.css";

const recursive = Recursive({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={recursive.className} suppressHydrationWarning>
      <main className="flex flex-col min-h-[calc(100vh-3.5rem-1px)]">
        {children}
      </main>
    </html>
  );
}
